# Generated by Django 3.2.9 on 2022-12-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Message'),
        ),
    ]
